version: "3"
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --default-authentication-plugin=mysql_native_password
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mysql_data:
